### ISSUE TITLE
Documentation for HPO website

### ISSUE THREAD

**Issue by pnrobinson** [data2health/ehr2HPO.prj#10]
We will write up documentation that will live on the main HPO website that will explain LOINC and the LOINC2HPO project. This will be linked to the new pages on the HPO website. It will also use material from #9

**Comment by kingmanzhang** [comment]
We have the documentation ready (the blog for the npj Digital Medicine paper). We need to re-publish it on our website.
https://github.com/TheJacksonLaboratory/hpo-web/issues/67

**Comment by kingmanzhang** [comment]
done. https://hpo.jax.org/app/tools/loinc2hpo
