### ISSUE TITLE
Implement synergy algorithm (test case)

### ISSUE THREAD

**Issue by pnrobinson** [data2health/ehr2HPO.prj#13]
Implement the algorithm described here and test it using artificial or genomic data as preparation for the CTSA analysis

Watkinson J, Wang X, Zheng T, Anastassiou D. Identification of gene interactions associated with disease from gene expression data using synergy networks. BMC Syst Biol. 2008;2:10.
Anastassiou D. Computational analysis of the synergy among multiple interacting genes. Mol Syst Biol. 2007;3:83.

**Comment by pnrobinson** [comment]
Initial summary of algorithm finished,

**Comment by kingmanzhang** [comment]
We have implemented the algorithm with python using the Numpy library. Numpy is a standard library for numeric computation. There is a Java counterpart, ND4J, if we want to implement this in Java.
