### ISSUE TITLE
Improve evaluation plan

### ISSUE THREAD

**Issue by mellybelly** [data2health/ehr2HPO.prj#20]
right now the eval plan is largely the same as the deliverables. It would be good to have some evaluation measures. 
What functionality will there be and how will you know the app has achieved it? 
How will you measure user satisfaction or query answering capabilities? 
What constitutes success? 

Here is a simple example of an evaluation plan with more of these sorts of items, you could copy the template: https://github.com/data2health/Operational-architecture/blob/master/evalulation.md

**Comment by pnrobinson** [comment]
Added this content
https://github.com/data2health/ehr2HPO.prj/blob/master/evaluation.md
thanks for the suggestions
