### ISSUE TITLE
i2b2 tutorial

### ISSUE THREAD

**Issue by pnrobinson** [data2health/ehr2HPO.prj#27]

**Comment by pnrobinson** [comment]
Write a tutorial for using the LOINC2HPO library (which emphasizes FHIR in the original publication) with datasets that are encoded using i2b2

**Comment by kingmanzhang** [comment]
The tutorial has been written:
https://github.com/monarch-initiative/loinc2hpo/blob/develop/docs/source/Consumption%20Tutorial.rst

It will appear here after we push to master:
https://loinc2hpo.readthedocs.io/en/latest/Tutorial.html
