### ISSUE TITLE
Demo needs clarification on scope / privacy

### ISSUE THREAD

**Issue by jmcmurry** [data2health/ehr2HPO.prj#28]
Here on the demo linked from labs, https://octri.ohsu.edu/hpo_on_fhir/, the language needs to change to either: 
 - clarify that the data is simulated/synthetic OR 
- state explicitly (with IRB number) that the data is real but can be shared. #6 says it is test data, which implies it is synthetic, but isn't crystal clear, especially in the demo.

**Comment by kingmanzhang** [comment]
done.
