### ISSUE TITLE
Ask the LOINC team about license issues

### ISSUE THREAD

**Issue by pnrobinson** [data2health/ehr2HPO.prj#3]
Is it allowable for us to add the LOINC mappings to the HPO website? Ask Daniel V exactly how we need to show the license

**Comment by kingmanzhang** [comment]
Email sent out.

**Comment by kingmanzhang** [comment]
We should include the following statement:
"This material contains content from LOINC® (http://loinc.org). The LOINC Table, LOINC Table Core, LOINC Panels and Forms File, LOINC Answer File, LOINC Part File, LOINC Group File, LOINC Document Ontology File, LOINC Hierarchies, LOINC Linguistic Variants File, LOINC/RSNA Radiology Playbook, and LOINC/IEEE Medical Device Code Mapping Table are copyright © 1995-2018, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license.”

We can close this ticket now.
