### ISSUE TITLE
Report on usage of LOINC2HPO at a CTSA site

### ISSUE THREAD

**Issue by pnrobinson** [data2health/ehr2HPO.prj#9]
We will write up a report with an analysis of the performance of the HPO on FHIR app at OHSU and diseminate it on the CD2H website.

**Comment by kingmanzhang** [comment]
We have done so with 28 million lab tests from intensive care unit patients. The performance is documented in a manuscript.

Aside this, @aeyates has tried this on OHSU data, and we also have coded a prototype to analyze JHU data.

**Comment by kingmanzhang** [comment]
Consider this as being done. Majority of failures are from lacking LOINC mapping, i.e. lab not coded with LOINC, which is not the scope of this project.
